### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by Seluj78** [Tagirijus/MantisBTDarkTheme#3]
Hi,

I'd like to create my own theme and be able to see the changes I make easily. How did you develop new themes ? Do you have a special setup that auto-reloads CSS when you make changes to a file ?

Cheers

**Comment by Tagirijus** [comment]
Hey there,

I am working with DDEV for website development: https://ddev.com/

My workflow then is: starting the local server / docker / environment with DDEV, changing code, literally just pressing F5 in my browser. :D

Regarding CSS it's even a bit more complicated, in a way, yet still ok to me workflow-wise: I am working with SASS and build the CSS, before I can press F5 in the browser then. Or more accurate: pressing _Ctrl+Shift+R_ to make even a hard refresh so that resources get refreshed as well - especially when it comes to CSS and JS.

So to your question: no, I do not have a special setup to **auto**-reload my files, yet I am working in a local environment before publishing stuff online.

I hope this helps you. Good luck! (=

**Comment by Seluj78** [comment]
Thanks a lot for the quick reply ! Does this apply also for this repository for MantisBT ?

**Comment by Tagirijus** [comment]
You are welcome. (= Yes. I also set up a DDEV environment for Mantis on my Linux machine. IIRC I did it in the root of Mantis and did all the DDEV settings _(you basically mainly edit a config YAML file in a subfolder called ".ddev" and then you are able to start the DDEV environment with `ddev start`)_. And then I have some git repos set up in the respecting plugin folders of this Mantis "installation" for keeping track my versions etc.. Works quite nice. I really like DDEV since it just works nicely so far. At least I remember it to be easier than running a whole Appache server in the background of my system.

Oh and I think here you can get further info on how to set everything up - no promise, though, since I did not re-check this link for a long time: https://ddev.readthedocs.io/en/latest/

Good luck, though. (=
